### ISSUE TITLE
Dodanie pól do problemu

### ISSUE THREAD

**Issue by marcmos** [zmora-agh/zmora-server#15]
Do realizacji https://github.com/zmora-agh/zmora-ui/issues/40 potrzeba dodać pola zwracane przy pobieraniu (listy) problemów: `category`, `deadline` i `points`.

**Comment by korrix** [comment]
Pole points nie może istnieć, bo to judge zwraca ilość punktów per submit, zadanie nie ma sztywno ustalonej tej wartości.

**Comment by marcmos** [comment]
@korrix czyli wyrzucić z tabeli problemów kolumnę `aktualna ilość punktów`?

**Comment by marcmos** [comment]
Proponuję jeszcze dodać informację, czy zadanie jest obowiązkowe.
