### ISSUE TITLE
Nieprawidłowa odpowiedź 401 serwera

### ISSUE THREAD

**Issue by maxmati** [zmora-agh/zmora-server#16]
na zapytanie 
```
curl 'https://api.zmora-agh.memleak.pl/contests/2' -H 'Pragma: no-cache' -H 'Origin: https://zmora-agh.github.io' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4' -H 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJkYXQiOnsibmljayI6Im1heG1hdGkiLCJuYW1lIjoiTWF0ZXVzeiBOb3dvdHluc2tpIiwiYWJvdXQiOiJvcGlzIiwiaWQiOjR9fQ.Wmyz5DOWGvBoagILtekJH5DB6jUJCnDizIOJJTys_kc' -H 'content-type: application/json' -H 'accept: application/json' -H 'Cache-Control: no-cache' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36' -H 'Connection: keep-alive' -H 'Referer: https://zmora-agh.github.io/contests/2/problems/30' --compressed -v
```
dostaje odpowiedź 
```
< HTTP/1.1 401 Unauthorized
< Date: Tue, 11 Apr 2017 17:23:38 GMT
< Server: Warp/3.2.11.1
< Access-Control-Allow-Origin: *
< Keep-Alive: timeout=5, max=100
< Connection: Keep-Alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host api.zmora-agh.memleak.pl left intact
Please authenticate in order to continue.⏎        
```

inne zapytanie z tym samym token JWT działa. Np:
```
curl 'https://api.zmora-agh.memleak.pl/contests/2/problems/30' -H 'Pragma: no-cache' -H 'Origin: https://zmora-agh.github.io' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4' -H 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJkYXQiOnsibmljayI6Im1heG1hdGkiLCJuYW1lIjoiTWF0ZXVzeiBOb3dvdHluc2tpIiwiYWJvdXQiOiJvcGlzIiwiaWQiOjR9fQ.Wmyz5DOWGvBoagILtekJH5DB6jUJCnDizIOJJTys_kc' -H 'content-type: application/json' -H 'accept: application/json' -H 'Cache-Control: no-cache' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36' -H 'Connection: keep-alive' -H 'Referer: https://zmora-agh.github.io/contests/2/problems/30' --compressed -v
```

**Comment by oszust002** [comment]
Odpowiedź 401 jest poprawna, brak tej odpowiedzi w przypadku problemów nie jest prawidłowa

**Comment by maxmati** [comment]
Dlaczego odpowiedź 401 jest poprawna? Jaki jest powód otrzymania tego błędu?

**Comment by oszust002** [comment]
nie dołączyłeś do contestu, dzisiaj @korrix dodawał dołączanie do contestu i przy okazji zablokował wejście do contestu jeśli do niego nie należysz

**Comment by maxmati** [comment]
To w takiej sytuacji ten contest powinien mi się nie pojawiać. Z tego co pamiętam to do contestu można dołączać do czasu jego rozpoczęcia.

**Comment by marcmos** [comment]
Problemy wczytują się za to bez problemu wszędzie. 😃

**Comment by oszust002** [comment]
To w takim razie bug na brak 401 przy problemach, zachowanie tego endpointu jest poprawne, po prostu filtrowanie contestów nie jest jeszcze wrzucone po stronie frontu. Zamykam.

**Comment by maxmati** [comment]
Skoro ma być to wycinane na froncie to szkoda tego w ogóle pchać przez sieć

**Comment by oszust002** [comment]
@maxmati mechanizmy filtrowania per user nie są zaimplementowane ani tu ani tu, jest to brak funkcjonalności, nie bug, więc nie rozumiem tego reopen (zwłaszcza że problem buga to tak naprawdę nie problem).

**Comment by maxmati** [comment]
Chce dokończyć dyskusje i ustalić jak to ostatecznie ma wyglądać

**Comment by maxmati** [comment]
Rozbite na #17 oraz #18

**Comment by korrix** [comment]
Obecnie tylko contesty są autoryzowane, problemy w contestach jeszcze nie, bo to wymaga zaklepania frameworka do uprawnień (bedę to męczył w święta)
